[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["N"]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # PEP 8 Naming conventions
    "N",
    # PEP 8 Warnings
    "W",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # Cyclomatic complexity issues from pylint
    "C9",
    # isort
    "I",
]
mccabe.max-complexity = 10
extend-select = ["I"]
exclude = [
    "docker",
    "deploy",
    "templates",
    "vm",
    "requirements",
    "media",
    ".env",
    "env",
    "node_modules",
    "braindrain",
    "samples",
    "logs",
    "data",
    "__pycache__",
    "build",
    "dist",
    "*_settings.py",
    "settings_*.py",
    "*migrations*",
    "venv",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.pycodestyle]
max-line-length = 120

[tool.ruff.lint.isort]
split-on-trailing-comma = true
force-single-line = true
